spring.application.name=SpringAI

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

spring.ai.vertex.ai.gemini.transport=rest
spring.ai.vertex.ai.gemini.project-id=spring-ai-study
spring.ai.vertex.ai.gemini.credentials-uri=classpath:spring-ai-study-e08977554fea.json
spring.ai.vertex.ai.gemini.location=us-central1

spring.ai.chat.client.enabled=false